onCreate:
  - |   
        pip install -r requirements.txt
        printf "\e[32mNow Go to .env file and paste your OpenAPI Key for e.g. OPENAI_API_KEY='YOUR_API_KEY'\e[0m\n"
        echo 'OPENAI_API_KEY="YOUR_API_KEY"' > .env
        mkdir knowledge_base tmp
        streamlit run main.py --server.enableCORS=false 

